Made By: **Adrian Earl Ng**
Section: **2ECE-C**

In [1]:
import pandas as pd

**A. POSITIONAL AND LABEL-BASED SLICING:** \
After loading cars, complete the following operations. \
**a.** Display the shape and complete list of column names of `cars.` \
**b.** Using positional slicing, create `cars_6_to_10` containing rows 6 through 10 of the dataset, where
the first data row is row 1. \
**c.** From `cars_6_to_10`, display only the columns `Model`, `mpg`, `cyl`, `hp`, and `gear`, in that order.

In [2]:
cars = pd.read_csv('cars.csv')
cars_6_to_10 = cars.iloc[5:10, [0, 1, 2, 4, 10]]
print ("Shape of Data Frame 'cars': ", cars.shape, "\n\n", cars.columns,"\n\nData Frame 'cars_6_to_10':")
cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

Shape of Data Frame 'cars':  (32, 12)

 Index(['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='str')

Data Frame 'cars_6_to_10':

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

-------------------------------------------------------------------------------

**B. MODEL LOOKUP:** \
Use Boolean indexing on the `Model` column to answer both requests. \
**a.** Display the complete row for `Toyota Corolla`. \
**b.** For `Pontiac Firebird`, display only `Model`, `mpg`, `hp`, and `wt`. \
\
Store the two results in `toyota` and `pontiac`, respectively. Do not use a hard-coded row number to locate either model.

In [3]:
toyota = cars.loc[cars['Model']=='Toyota Corolla']
pontiac = cars.loc[cars['Model']=='Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']]
toyota

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [4]:
pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

---------------------------------------------------------------------------------------------------------------

**C. MULTI-MODEL SUBSETTING:** \
Create a DataFrame named `selected_cars` containing only the records for three models: `Datsun 710`, `Lotus Europa`, and `Ferrari Dino`. \
\
For these records, retain only `Model`, `mpg`, `cyl`, `hp`, and `gear`. Select the rows by their model values rather than by row numbers. Display `selected_cars` and its shape.

In [5]:
selected_cars = cars.loc[(cars['Model']=='Datsun 710') | (cars['Model']=='Lotus Europa') | (cars['Model']=='Ferrari Dino'), ['Model', 'mpg', 'cyl', 'hp', 'gear']]
print ("Shape of Data Frame 'selected_cars'", selected_cars.shape, "\n\nData Frame 'selected_cars':")
selected_cars

Shape of Data Frame 'selected_cars' (3, 5)

Data Frame 'selected_cars':

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5